export type Role = "admin" | "manager" | "employee" | "mdtsAdmin";

export const Permissions = {
    VIEW_NAVBAR_MENUS: ["admin", "manager", "employee"],
    CREATE_MODULE: ["admin", "manager"],
    DELETE_MODULE: ["admin", "manager"],
    EDIT_MODULE: ["admin", "manager"],
    CREATE_MDTS_MODULE: ["mdts_admin"],
    CONVERT_PERSONAL_TO_ORG_MODULE: ["admin", "manager"],
    CREATE_MINE_TYPE: ["admin", "manager"],
    IMPORT_DATA: ["admin", "manager"],
    IMPORT_MODULE_FROM_OTHER_SOURCE: ["admin", "manager"],
    IMPORT_FROM_MDTS: ["admin", "manager"],
    IMPORT_FROM_ORGANIZATIONS: ["admin", "manager"],
    ADD_DOCUMENT_IN_ACTIVITY: ["admin", "manager"],
    ADD_COST_IN_ACTIVITY: ["admin", "manager"],
    ASSIGN_RASI: ["admin", "manager"],
    CREATE_NEW_Module: ["admin", "manager"],
    LEVEL_UP_DOWN: ["admin", "manager"],
    SET_NOTIFICATIONS: ["admin", "manager"],
    SET_GLOBAL_NOTIFICATIONS: ["admin", "manager"],
    CREATE_GROUP: ["admin", "manager"],
    EDIT_GROUP: ["admin", "manager"],
    DELETE_GROUP: ["admin", "manager"],
    CREATE_PROJECT: ["admin", "manager"],
    EDIT_PROJECT: ["admin", "manager"],
    DELETE_PROJECT: ["admin", "manager"],
    BUILD_TIMEBUILDER: ["admin", "manager"],
    SELECT_APPROVER_FOR_TIMELINE: ["admin", "manager"],
    UPDATE_STATUS: ["admin", "manager"],
    APPROVE_TIMELINE: ["admin", "manager"],
    REJECT_TIMELINE: ["admin", "manager"],
    EDIT_TIMELINE: ["admin", "manager"],
    SET_GLOBAL_HOLIDAY: ["admin", "manager"],
    EDIT_HOLIDAY: ["admin", "manager"],
    DELETE_HOLIDAY: ["admin", "manager"],
    ADD_GLOBAL_DOCUMENT: ["admin", "manager"],
    VIEW_TEAM_MEMBERS: ["admin", "manager", "employee"],
    VIEW_PROJECT_LIST: ["admin", "manager", "employee"],
    ADD_TEAM_MEMBER: ["admin"],
    EDIT_TEAM_MEMBER: ["admin"],
    REMOVE_TEAM_MEMBER: ["admin"],
    ASSIGN_ROLE_TO_TEAM_MEMBER: ["admin"],
    DPR_COST_BUILDER: ["admin", "manager", "employee"],
    CASH_FLOW_BUILDER: ["admin", "manager", "employee"],
    DELAY_COST_CALCULATOR: ["admin", "manager", "employee"],

} as const;

export type Permission = keyof typeof Permissions;
